import { sqliteTable, text, integer, real, index, uniqueIndex, primaryKey } from 'drizzle-orm/sqlite-core';
export const employees = sqliteTable('employees', {id:text('id').primaryKey(),name:text('name').notNull(),active:integer('active').notNull().default(1)});
export const customers = sqliteTable('customers', {
 id:text('id').primaryKey(),name:text('name').notNull(),contact:text('contact').notNull().default(''),classification:text('classification').notNull().default(''),email:text('email').notNull().default(''),phone:text('phone').notNull().default(''),status:text('status').notNull().default('Nýr'),notes:text('notes').notNull().default(''),created:text('created').notNull(),
 ownerId:text('owner_id').references(()=>employees.id),address:text('address').notNull().default(''),nationalId:text('national_id').notNull().default(''),invoiceNumbers:text('invoice_numbers').notNull().default(''),purchaseNotes:text('purchase_notes').notNull().default(''),paydayUrl:text('payday_url').notNull().default(''),sourceKey:text('source_key'),
},t=>[uniqueIndex('idx_customers_source_key').on(t.sourceKey)]);
export const interactions = sqliteTable('interactions', {id:text('id').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id),kind:text('kind').notNull(),sold:integer('sold').notNull().default(0),body:text('body').notNull(),ownerId:text('owner_id').references(()=>employees.id),created:text('created').notNull()},t=>[index('idx_interactions_customer').on(t.customerId)]);
export const tasks = sqliteTable('tasks', {id:text('id').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id),title:text('title').notNull(),due:text('due').notNull(),done:integer('done').notNull().default(0),ownerId:text('owner_id').references(()=>employees.id),created:text('created').notNull()},t=>[index('idx_tasks_customer').on(t.customerId)]);
export const products = sqliteTable('products',{id:text('id').primaryKey(),name:text('name').notNull()},t=>[uniqueIndex('idx_products_name').on(t.name)]);
export const customerProducts = sqliteTable('customer_products',{customerId:text('customer_id').notNull().references(()=>customers.id,{onDelete:'cascade'}),productId:text('product_id').notNull().references(()=>products.id)},t=>[primaryKey({columns:[t.customerId,t.productId]})]);
export const invoiceLines = sqliteTable('invoice_lines',{
 id:text('id').primaryKey(),customerId:text('customer_id').notNull().references(()=>customers.id,{onDelete:'cascade'}),date:text('date').notNull().default(''),invoiceNumber:text('invoice_number').notNull().default(''),category:text('category').notNull().default(''),description:text('description').notNull().default(''),quantity:real('quantity'),unitPrice:real('unit_price'),totalWithVat:real('total_with_vat'),totalWithoutVat:real('total_without_vat'),discount:text('discount').notNull().default(''),status:text('status').notNull().default(''),notes:text('notes').notNull().default(''),paydayUrl:text('payday_url').notNull().default(''),
},t=>[index('idx_invoice_lines_customer').on(t.customerId)]);
